### ISSUE TITLE
只有你一个人翻译吗？

### ISSUE THREAD

**Issue by adaaaaaa** [Kivy-CN/CS229-CN#1]
多叫几个人一起啊。。。才一个人进度太慢了。。。而且，质量可能也没那么好吧？

**Comment by cycleuser** [comment]
STA663 目前是 飞龙 在翻译第七章以后的内容
CS 229 目前只有我一个人，质量不好这个是最大的问题，多拉人确实好，不过没找到人。。。这是个问题。。。

**Comment by howard-hou** [comment]
我在翻译STA663的code optimization

**Comment by wizardforcel** [comment]
希望 LZ 能参与进来，一边看着已有的笔记一边翻译也好。

**Comment by vyfe** [comment]
刚开始看这个公开课……暑假说不定有时间，可以帮忙翻译一点的

**Comment by cycleuser** [comment]
唉，基本翻译完了，这个 CS229，全部的12 个 notes 居然还真就是我一个人翻译的，然后一些额外的补充资料，另外的一个朋友在翻译，不过进度比较缓慢，主要是矩阵和线性代数方面的基础知识。

目前我先把中文译稿重制成 Markdown，这个过程是重新一边阅读原版一边修改中文稿件，一边复制修改 Markdown，手打公式成 LaTeX 文本。

大家如果有参与的想法，欢迎来审阅挑错或者以同样方式来参与制作 Markdown 文本。
