### ISSUE TITLE
其他人的笔记

### ISSUE THREAD

**Issue by wizardforcel** [Kivy-CN/CS229-CN#11]
[stdcoutzyx](https://github.com/Kivy-CN/Stanford-CS-229-CN/files/2343330/cs229-stdcoutzyx.pdf)

[JerryLead](https://github.com/Kivy-CN/Stanford-CS-229-CN/files/2343386/cs229-JerryLead.pdf)

[黄海广](https://github.com/fengdu78/Coursera-ML-AndrewNg-Notes)

**Comment by Sierkinhane** [comment]
我用Python 实现了cs229中的算法https://github.com/Sierkinhane/CS229-ML-Implements
