### ISSUE TITLE
Note3的html/pdf？

### ISSUE THREAD

**Issue by shouldsee** [Kivy-CN/CS229-CN#2]
https://github.com/Kivy-CN/Stanford-CS-229-CN/blob/master/%E4%B8%AD%E6%96%87%E7%BF%BB%E8%AF%91%E4%B8%AD/notes/cs229-notes3.docx
麻烦能不能转成html方便阅览？多谢。

**Comment by cycleuser** [comment]
好滴，稍等

**Comment by cycleuser** [comment]
HTML 已经生成了，其实我就是用 Word 另存成的 HTML。

之前第一章的 PDF 是 @yuanqili  帮忙制作的，用到了 LaTeX 来生成公式之类的，而且经过非常精心的校对。我目前精力比较有限，所以可能还只能主要着重在往后翻译的上面，文中存在不确定性或者对质量很没信心的部分，我都会保留英文原文，或者标识出来之类的。

如果有兴趣，欢迎提出修改建议哈，帮给挑挑错误啥的哈~ 非常感谢！

**Comment by shouldsee** [comment]
好的好的，我有空稍微来看看。辛苦啦！
不过，看起来MarkDown比HTML更方便啊，希望多加几份markdown。另外，你是直接用Word生成html/md的吗？因为我平时只能用LibreOffice不太兼容Word...

**Comment by cycleuser** [comment]
@shouldsee  嗯，是用 Word 导出的，我目前身体状况比较狗带，所以主要精力还要放到翻译上面，对于文件格式可能暂时没办法抽出足够精力了，话说是否有兴趣加入我们来帮忙搞一下文件格式呢？

**Comment by shouldsee** [comment]
我找了一个暂时的Markdown解决方案，最好还是能转成Latex并形成一套流程。但是我本人对Latex不熟。 #3

**Comment by cycleuser** [comment]
目前我先把中文译稿重制成 Markdown，这个过程是重新一边阅读原版一边修改中文稿件，一边复制修改 Markdown，手打公式成 LaTeX 文本，等 Markdown 做好之后，导出 pdf 和 html 应该也就很容易了
