### ISSUE TITLE
项目内容还缺几章翻译呀

### ISSUE THREAD

**Issue by Dongzhixiao** [Kivy-CN/CS229-CN#25]
项目中内容除了缺少所有讨论课(Discussion Section)笔记外，课堂笔记(Discussion Section)中还缺少以下几篇：

- 1. 决策树[(Decision trees)](http://cs229.stanford.edu/notes/cs229-notes-dt.pdf)
- 2. 集成学习[(Ensembling Methods)](http://cs229.stanford.edu/notes/cs229-notes-ensemble.pdf)
- 3. 深度学习[(Deep Learning)](http://cs229.stanford.edu/notes/cs229-notes-deep_learning.pdf)
- 4. 反向传播算法[(Backpropagation)](http://cs229.stanford.edu/notes/cs229-notes-backprop.pdf)
- 5. 线性二次系统，微分动态规划和线性二次高斯[(LQR, DDP and LQG)](http://cs229.stanford.edu/notes/cs229-notes13.pdf)

如果能够补充完整就最好啦~

**Comment by Dongzhixiao** [comment]
:point_right: [这个地址：](http://cs229.stanford.edu/syllabus.html)`http://cs229.stanford.edu/syllabus.html`是所有课程讲义的地址。我是按照这个网页整理的缺少的章节。:blush:

顺便感谢下翻译的人，内容非常棒！:thumbsup: 我准备再精读下~

**Comment by wizardforcel** [comment]
这些应该都没有。。

如果算上`extra-notes`和`section`里面的东西，缺的还多。

**Comment by Dongzhixiao** [comment]
因为现在翻译过的12篇都属于`课堂笔记(Discussion Section)`，所以我列出了的这五篇也是课堂笔记。如果这五篇加上的话当做一个系列就比较完整了，真遗憾啊 :sob:

**Comment by cycleuser** [comment]
@Dongzhixiao 

非常感谢制作Markdown以及指出更新的内容! 

两年前刚开始翻译的时候从CS229网站下载的讲义中可能没包含这部分内容.
现在看到了是真棒. 要是凑齐确实比较好.
奈何目前我忙于其他事物可能**半年内都未必能抽出时间**. 
最理想的情况也要到**劳动节以后**.

好在只有五章,估计是没有太多篇幅, 等我有时间一定来继续补齐.

**Comment by Dongzhixiao** [comment]
> @Dongzhixiao
> 
> 非常感谢制作Markdown以及指出更新的内容!
> 
> 两年前刚开始翻译的时候从CS229网站下载的讲义中可能没包含这部分内容.
> 现在看到了是真棒. 要是凑齐确实比较好.
> 奈何目前我忙于其他事物可能**半年内都未必能抽出时间**.
> 最理想的情况也要到**劳动节以后**.
> 
> 好在只有五章,估计是没有太多篇幅, 等我有时间一定来继续补齐.

感谢@cycleuser的无私奉献，期待您的更新~

**Comment by cycleuser** [comment]
新增的这五个章节已经完成翻译, 格式为Markdown文档, 直接放在了[Markdown](https://github.com/Kivy-CN/Stanford-CS-229-CN/blob/master/Markdown)目录下.

* 1. 深度学习[(Deep Learning)](https://github.com/Kivy-CN/Stanford-CS-229-CN/blob/master/Markdown/cs229-notes-deep_learning.md)
* 2. 反向传播算法[(Backpropagation)](https://github.com/Kivy-CN/Stanford-CS-229-CN/blob/master/Markdown/cs229-notes-BP.md)
* 3. 线性二次系统，微分动态规划和线性二次高斯[(LQR, DDP and LQG)](https://github.com/Kivy-CN/Stanford-CS-229-CN/blob/master/Markdown/cs229-notes13.md)
* 4. 决策树[(Decision trees)](https://github.com/Kivy-CN/Stanford-CS-229-CN/blob/master/Markdown/cs229-notes-dt.md)
* 5. 集成学习[(Ensembling Methods)](https://github.com/Kivy-CN/Stanford-CS-229-CN/blob/master/Markdown/cs229-notes-ensemble.md)
