### ISSUE TITLE
网页上的目录显示有些问题

### ISSUE THREAD

**Issue by Dongzhixiao** [Kivy-CN/CS229-CN#34]
两个问题如下：

- 强化学习（Reinforcement Learning）和控制（Control）在原文中是第十三部分，不好意思，我第一次提交Markdown的时候写错了，现在网页上的目录显示有些问题
- 线性二次调节，微分动态规划，线性二次高斯分布是第十四部分

我推测是网页的目录在summary.md里面改，但是不确定，就把问题放在这里提出，等@wizardforcel 如果看到帮忙修改下，谢谢~

**Comment by wizardforcel** [comment]
改完了~
