### ISSUE TITLE
pdf版本

### ISSUE THREAD

**Issue by serkun** [Kivy-CN/CS229-CN#4]
感谢楼主的辛苦翻译，方便了我这种英语渣的学习。我发现md、docx文件都存在瑕疵，pdf文件是最完美的，打印下来看着很舒服。麻烦楼主有空将note2以后的pdf版本补上。再次感谢！

**Comment by shouldsee** [comment]
PS: .md格式主要方便在线浏览，可惜公式上下标显示太糟。打印下来读的确是很好的一种阅读方法。

**Comment by cycleuser** [comment]
@serkun  

> 之前第一章的 PDF 是 @yuanqili 帮忙制作的，用到了 LaTeX 来生成公式之类的，而且经过非常精心的校对。我目前精力只能着重在翻译上，文中存在不确定性或者对质量很没信心的部分，我都会保留英文原文，或者标识出来之类的。校对，以及格式，都没有办法去保证质量，甚至根本不会弄。

刚刚添加的 PDF 也只是用 Word 将文件导出成了 PDF，HTML 文件也是这么来的。

所以很抱歉，目前我没能力提供更高质量的 PDF，目前只能期待参与的人越来越多，有专门擅长这一块的朋友来参与进来。

**Comment by pjpjq** [comment]
PDF不是用 LaTeX 编译的么...

**Comment by cycleuser** [comment]
目前我先把中文译稿重制成 Markdown，这个过程是重新一边阅读原版一边修改中文稿件，一边复制修改 Markdown，手打公式成 LaTeX 文本，等 Markdown 做好之后，导出 pdf 和 html 应该也就很容易了。
