### ISSUE TITLE
请问Section Notes里面的凸优化有人翻译么？没有的话我想接手翻译~

### ISSUE THREAD

**Issue by Dongzhixiao** [Kivy-CN/CS229-CN#43]
Motivation: 

- 凸优化是机器学习中**优化问题的基础**。
- 其他几个Section notes（比如[线性代数](http://cs229.stanford.edu/section/cs229-linalg.pdf)和[概率论](http://cs229.stanford.edu/section/cs229-prob.pdf)）大部分理工科生本科都作为专业课学过，而以**凸优化作为专业课**的专业**相对较少**，所以学习翻译凸优化的内容很有必要(**优先级较高**)。
- [原版](https://web.stanford.edu/~boyd/cvxbook/bv_cvxbook.pdf)凸优化内容较多，阅读很费劲，section notes([凸优化1](http://cs229.stanford.edu/section/cs229-cvxopt.pdf)以及[凸优化2](http://cs229.stanford.edu/section/cs229-cvxopt.pdf))中抽出机器学习中需要的部分，**内容比较少，利于快速学习入门**。

**Comment by wizardforcel** [comment]
没有，欢迎翻译~

**Comment by Dongzhixiao** [comment]
> 
> 
> 没有，欢迎翻译~

恩，好的，那我这里先占个坑，翻译完成后再close

**Comment by Dongzhixiao** [comment]
## 凸优化1翻译进度

|内容主要标题|进度|
|---|---|
|1 介绍|100%|
|2 凸集|100%|
|3 凸函数|100%|
|4 凸优化问题|100%|

## 凸优化2翻译进度

|内容主要标题|进度|
|---|---|
|1 拉格朗日对偶|100%|
|2 一个简单的对偶实例|100%|
|3 svmL1范数的软边界|100%|
|4 后续研究方向|100%|

2019-3-16备注（已修改）：
1. 修改凸优化1内连接【2】无效的问题
2. 增加凸优化2内“详情请点击本行”

2019-3-17备注（待修改）：
1. Jensen不等式积分形式写错了
2. 半正定、半负定错写成正半定、负半定了！
3. 4.1第一段第二行语句不通
4. 4.2 半定规划缺了一个X
5. 4.3 SVM QP括号写错了
6. 凸优化2 第一段c应该是大写

**Comment by Dongzhixiao** [comment]
已**完成**Section Notes里面**凸优化所有的翻译。**
顺便吐槽一下：
- 项目中资料太多，建议**分仓库存储。** 
- 得到存储后**资料的连接。**
- 每个文件中通过README.md文件给出**资料的连接**即可。

否则每次在一个新的机器上翻译&校对的时候（需要拉取整个项目）尽管我pull的深度是1，也特别慢……特别是网络不好的时候中间经常断（春节回家我有一次为了校对，结果pull了一天都没有pull下来）
