### ISSUE TITLE
我或许可以帮助你维护一个Gitbook版本

### ISSUE THREAD

**Issue by 0xMashiro** [Kivy-CN/CS229-CN#5]
如果你认为需要这方面的帮助的话

**Comment by cycleuser** [comment]
嗯，确实非常有必要！

之前的 ThinkPython 和 Kivy-CN 以及 @wizardforcel 的一些书也都是放到 Gitbook，阅读体验明显好了很多。

话说目前总体翻译的进度，大概是 notes 一共 12个，正在翻译最后一个，然后额外的资料，估计要先翻译 extra notes。

已经翻译的内容里面存在一些严重问题：
首先是有的地方的翻译质量还有问题，我把自己不太有把握的语句用黄色背景标注在了 Wrod 文档里面。
第二个问题是所有公式都还是截图，要是做 Gitbook 的话，可能还是得用 LaTeX 之类的在 Markdown 里面写成公式。

眼下我最拙计的就是 LaTeX，短期无法掌握，然后自己把握不准的语句，也没有什么办法。

话说在这两方面可能是亟待提高改善的。

这两个弄好之后，就可以制作出来质量更好一些的 Markdown 文档，做 Gitbook 也就方便了一些了。

**Comment by sweird1** [comment]
如果需要的话，latex公式我可以提供部分，目前已经完成前三讲，第四讲正在整理。

**Comment by 0xMashiro** [comment]
既然也有通过md版本整理的话，那么后面转为gitbook会非常方便了，眼下认为先完成当前的翻译工作后再进行gitbook方面的工作，比较合适。

**Comment by wizardforcel** [comment]
@cycleuser 截图其实也没问题，只要图片够清晰就可以了。

知乎有个 Tex 公式转图片的接口，可以试试：<https://www.zhihu.com/equation?tex=\vec{ab}>

还有就是，一旦有了 Markdown 文件，就没必要再去改 Word，然后 PDF 也可以从 Markdown 生成（<https://stackedit.io>），这样比较省力。

**Comment by shouldsee** [comment]
@cycleuser 你现在的主要编辑格式是不是.docx?

**Comment by cycleuser** [comment]
@shouldsee 

我这一个月先后患上了肺炎和气管炎，在翻译完了全部 12 个 notes 之后没有继续翻译其他。

**Comment by shouldsee** [comment]
@cycleuser 哦要注意身体呐！

我是想问大部分的翻译原稿是用Word编辑的对吗？然后公式的插入也是用Word吗？还是说接下来会考虑另外的编辑器呢？

如果公式都是截图的话， 我可以找到的图片大多在.fld下面，形式为png，但是在 #7 中已经提到图片的编号并不总是正确。比如 [notes/cs229-notes3.fld/](https://github.com/Kivy-CN/Stanford-CS-229-CN/tree/master/%E4%B8%AD%E6%96%87%E7%BF%BB%E8%AF%91%E4%B8%AD/notes/cs229-notes3.fld) 下的 [image059.png](https://raw.githubusercontent.com/Kivy-CN/Stanford-CS-229-CN/master/%E4%B8%AD%E6%96%87%E7%BF%BB%E8%AF%91%E4%B8%AD/notes/cs229-notes3.fld/image059.png) 和 [image060.png](https://raw.githubusercontent.com/Kivy-CN/Stanford-CS-229-CN/master/%E4%B8%AD%E6%96%87%E7%BF%BB%E8%AF%91%E4%B8%AD/notes/cs229-notes3.fld/image060.png) 就是重复的，原因未明

**Comment by cycleuser** [comment]
@shouldsee 嗯，翻译原稿都是 Word，在原稿中公式都是截图。未来还是希望能转成 Markdown ，好像是可以在 Markdown 内部使用 LaTeX 公式那就是最好了，这样编辑和阅读很方便。
现在的 Markdown 对文字内部的变量符号的表述可能都还需要改进。

**Comment by shouldsee** [comment]
#### passed (escaped):
tex_str = "O_t=\text{%20Onset%20event%20at%20time%20bin%20}%20t"
![equation](http://latex.codecogs.com/gif.latex?O_t=\text{%20Onset%20event%20at%20time%20bin%20}%20t)
<img src="https://latex.codecogs.com/gif.latex?O_t=\text{%20Onset%20event%20at%20time%20bin%20}%20t" /> 

#### failed (raw string):
tex_str = "O_t=\text { Onset event at time bin } t"
![equation](http://latex.codecogs.com/gif.latex?O_t=\text { Onset event at time bin } t )
<img src="https://latex.codecogs.com/gif.latex?O_t=\text { Onset event at time bin } t " /> 

#### codecogs:
![equation](https://latex.codecogs.com/gif.latex?O_t=\text{%20Onset%20event%20at%20time%20bin%20}%20t)

#### zhihu:
![equation](https://www.zhihu.com/equation?tex=O_t=\text{%20Onset%20event%20at%20time%20bin%20}%20t)

### 结论： 
URL必须escape才能使用，至少要用%20替代空格
