### ISSUE TITLE
感谢楼楼的无私奉献，么么哒！

### ISSUE THREAD

**Issue by cCurious** [Kivy-CN/CS229-CN#6]
楼楼有时间能把那个section note翻译一下么，就是那个复习数学基础的那个，谢谢！数学渣实在伤不起

**Comment by cycleuser** [comment]
嗯，好的，本来打算是翻译完 notes 之后翻译 extra notes，不过看来 section note 也有必要翻译一下了。
其实我数学就很渣。。。基本都是一边翻译一遍预习。。。
我问问身边数学比较扎实的同学，看看他有没有兴趣来翻译。
其实很建议你来尝试加入我们来翻译一下啊，怎么样~~~

**Comment by cCurious** [comment]
今天花了两小时翻译，才到第四页，我也很绝望啊。

**Comment by cycleuser** [comment]
@cCurious  嗯，刚开始往往就是容易稍微吃力一些，别着急，慢慢来，有苦难的地方就先标记出来绕过去，凡事其实开头大多如此，正所谓不积跬步无以至千里，加油加油！

**Comment by cCurious** [comment]
共勉。

**Comment by cycleuser** [comment]
@cCurious  查收一下邮件哈，邀请加入维护了，Github 的邮件可能被 QQ 邮箱之类的收入垃圾邮件。

**Comment by cCurious** [comment]
已加入，感谢楼楼，么么哒！
