### ISSUE TITLE
note3-3.函数边界和几何边界 章节中 公式乱的

### ISSUE THREAD

**Issue by kevin-gjm** [Kivy-CN/CS229-CN#7]
note3.md中
3 函数边界和几何边界（Functional and geometric margins）
里面的公式有重复，位置不对

**Comment by cycleuser** [comment]
@kevin-gjm  我对 Markdown 还真不是太熟悉，话说可否愿意加入来进行维护呢~ 强烈欢迎啊！

**Comment by kevin-gjm** [comment]
@cycleuser  乐意至极。这样更能督促我学习了

**Comment by shouldsee** [comment]
@kevin-gjm notes3.md的Markdown 是用[Typora](https://typora.io/)打开 *.docx 以后重新保存得到的。
见 #3

**Comment by kevin-gjm** [comment]
我正在一边对照英文一边学习，我想在学习过程中，碰到有公式问题的地方进行修改。
修改方式使用在线的公式编辑器下方连接。使用图片或者连接方式进行替换.然后慢慢全部替换。@shouldsee @cycleuser
https://www.codecogs.com/eqnedit.php

**Comment by cycleuser** [comment]
目前正在检查，同时制作 Markdown 文本，所有公式都在 Markdown 中使用 LaTeX 重新写出，刚刚重写了第一章的一半左右。

有兴趣的朋友们，可以各自认领一章，来进行基于Word 制作 Markdown 文件，建议不要使用任何转换工具，尽量一边阅读原版和译稿，同时复制粘贴修改 Markdown，这样能保证公式的准确性，推导过程也有所理解。

如果只是机械地转换格式，就失去了学习的效果了。
