### ISSUE TITLE
Hello, I may have found some mistakes.

### ISSUE THREAD

**Issue by lzw-all-in** [Kivy-CN/CS229-CN#71]
1. 第七部分贝叶斯统计公式一有错分子多了一个p(theta)

2. 同样第七部分：“因此在实际应用中，我们都是用一个与 \thetaθ 的后验分布 (posterior distribution)近似的分布来替代。常用的一个近似是把对 \thetaθ 的后验分布(正如等式(2) 中所示)”
 应该是正如等式(1)中所示

**Comment by cycleuser** [comment]
cs229-notes7a和7b这两个文档中都没找到对应的位置.
希望直接指出到底是哪个文档文件内, 或者可以直接修改然后推送上来.这样效率高很多.

**Comment by Dongzhixiao** [comment]
@lzw-all-in 感谢指出错误！
- 您指出的第一个问题**以修改并提交请求合并，** 但
- 第二个问题的原文摘抄如下：
>Thus, in practice we will instead approximate the posterior distribution for θ. One common approximation is to replace our posterior distribution for θ (as in Equation **_2_** ) with a single point estimate.

原文中就是**等式(2)(Equation2)**，请问您的意思是[原文](https://github.com/Kivy-CN/Stanford-CS-229-CN/blob/master/CS229%E5%AE%98%E7%BD%91%E5%BD%93%E5%89%8D%E6%96%87%E6%A1%A3/notes/cs229-notes5.pdf)有误么？

**Comment by cycleuser** [comment]
长期无后续回应，先关闭了。
