### ISSUE TITLE
支持向量部分细节错误

### ISSUE THREAD

**Issue by rockj2016** [Kivy-CN/CS229-CN#77]
https://github.com/Kivy-CN/Stanford-CS-229-CN/blob/master/Markdown/cs229-notes3.md#5-%E6%8B%89%E6%A0%BC%E6%9C%97%E6%97%A5%E5%AF%B9%E5%81%B6%E6%80%A7lagrange-duality

翻译
>  这个等式暗示，当$\alpha_i^\ast \geq 0$ 的时候

原文
>  Specifically, it implies that if α∗i > 0,

---

https://github.com/Kivy-CN/Stanford-CS-229-CN/blob/master/Markdown/cs229-notes3.md#6-%E6%9C%80%E4%BC%98%E8%BE%B9%E7%95%8C%E5%88%86%E7%B1%BB%E5%99%A8optimal-margin-classifiers-

翻译
> 另外，之前我们就已经发现所有支持向量(support vectors)的 \alpha_iα i的值都是 0。

原文
> . Moreover, we saw earlier that the αi’s will all be zero except for the support vectors.

**Comment by Dongzhixiao** [comment]
感谢您的指正，已修改~
