### ISSUE TITLE
机器学习课件翻译的另一个版本

### ISSUE THREAD

**Issue by Maecenas** [Kivy-CN/CS229-CN#8]
www.scribd.com/document/356519852/机器学习个人笔记完整版v4-3

**Comment by cycleuser** [comment]
这个网站需要**填写信用卡信息**才能下载文档，而在线浏览的体验很差，建议用其他更开放的获取方式进行分享。

另外这份笔记似乎更多是个人笔记，而不完全是课件翻译。
