### ISSUE TITLE
感谢楼主的辛苦翻译，可否提供一下所有内容的最终版pdf文件？

### ISSUE THREAD

**Issue by Tao-Zhou** [Kivy-CN/CS229-CN#80]

**Comment by Dongzhixiao** [comment]
有以下**两种方法**可供选择：
- 第一种方法：可以使用浏览器的PDF打印时的**保存功能**，Chrome浏览器默认的PDF打印可以参考[这里](https://jingyan.baidu.com/article/5bbb5a1b1d857413eaa17946.html)。
- 第二种方法：如果感觉Chrome等浏览器默认的PDF打印效果不理想，还可以参考[Print Friendly & PDF插件](https://zhaoolee.gitbooks.io/chrome/content/035print-friendly-and-pdf.html)。
>注：**第二种方法下载插件时**可能需要**科学上网**（即：翻越国内的墙）——**github上免费的科学上网工具**可以参考[这里](https://zhaoolee.gitbooks.io/starsandclown/content/qi-liao-699c5d-fan-qiang-fang-fa-ji-he.html)。(PS：免费工具虽然速度不快，但是**下载个插件绰绰有余**了)

**Comment by cycleuser** [comment]
建议自己下载pdf然后合并。
