### ISSUE TITLE
请问这是课程讲义的翻译还是课程笔记呢？

### ISSUE THREAD

**Issue by jiahe224** [Kivy-CN/CS229-CN#81]
请问这是课程讲义的翻译还是课程笔记呢？印象中原课程好像没有讲义，所以想问问是原讲义的翻译还是类似黄海广博士那样的课程笔记

**Comment by cycleuser** [comment]
http://cs229.stanford.edu/

![image](https://user-images.githubusercontent.com/6130092/59166738-55d9c580-8b5f-11e9-8f6e-d0b0781b04db.png)
