### ISSUE TITLE
公式显示错误

### ISSUE THREAD

**Issue by potatoker** [Kivy-CN/CS229-CN#82]
![image](https://user-images.githubusercontent.com/5286501/62418758-01a51a80-b6a4-11e9-9ce5-32fd54dfba5f.png)

今天突然发现chrome和safari上公式的都成了原始的mrkdown语法，辛苦看下是不是网站的某个插件失效了~

**Comment by cycleuser** [comment]
刚刚使用 Chrome 75.0.3770.142 和  76.0.3809.87 测试了一下，一切正常。
![image](https://user-images.githubusercontent.com/6130092/62418874-84c77000-b6a6-11e9-81b2-c3a30bb66918.png)

**Comment by potatoker** [comment]
好吧，我也是这个版本的： mac最新版  76.0.3809.87，但是显示不出公式
![image](https://user-images.githubusercontent.com/5286501/62418948-24393280-b6a8-11e9-9acd-a7c85affcf1f.png)

**Comment by cycleuser** [comment]
群里有其他macOS用户反映一切正常。

> safari chrome firefox ipad均正常


你所遇到的情况超出我们力所能及的范围了。
