### ISSUE TITLE
网页版第六部分，无限个假设（Infinite）的情况中公式存在错误

### ISSUE THREAD

**Issue by Elnath-123** [Kivy-CN/CS229-CN#85]
[https://kivy-cn.github.io/Stanford-CS-229-CN/#/Markdown/cs229-notes4](url)
最后一个公式
“此外，有至少为1-δ的概率：
        此公式第一项应该是ε(h^hat)而不是ε^hat(h)
”

**Comment by cycleuser** [comment]
好滴，收到，稍等我这就修正。
