### ISSUE TITLE
note2中出现的错误

### ISSUE THREAD

**Issue by zhoucz97** [Kivy-CN/CS229-CN#88]
cs229-notes2.docx这个文档的第12页最后一行。
原文写的是φj|y=1 is正是垃圾邮件中单词 j 出现的邮件中垃圾邮件所占（y = 1）的比例。
是不是应该改成φj|y=1 是垃圾邮件中单词 j所占的比例。

**Comment by cycleuser** [comment]
感谢指正，我现在访问GitHub受阻，麻烦修正后提交PL吧，多谢了。
