### ISSUE TITLE
网页版第四部分公式错误

### ISSUE THREAD

**Issue by KazakiX** [Kivy-CN/CS229-CN#95]

**Comment by KazakiX** [comment]
![SF24251E@$WR8~NR@@ZQY_L](https://user-images.githubusercontent.com/42568327/143197328-1f9a26a8-c7a2-48e6-80d0-b0465df734c0.png)
对比
![K7ZP58AJ5KKSB$U$ OD75C3](https://user-images.githubusercontent.com/42568327/143197377-c0d8772a-22e7-4e1f-8f5a-b1ad391f7946.png)
应该是y=0

**Comment by cycleuser** [comment]
收到，等我看一下改掉

**Comment by cycleuser** [comment]
刚刚的推送中修改了md格式的来，其他格式的我找不过来了，大家谁看到就顺路改了推送上来即可。
